name: Ubuntu unit tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: unit-ubuntu
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        # Test oldest. Latest is tested by coverage
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v6

      - name: Configure Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install
        run: |
          python --version
          python -m pip install .

      - name: Run unit tests
        run: |
          python -m unittest

